### ISSUE TITLE
npm请提一小版

### ISSUE THREAD

**Issue by hezedu** [node-webot/wechat-corp-service#13]
不然README.md 上的 `apiProvider.generateAuthUrl`例子是错的.

**Comment by JacksonTian** [comment]
文档更新不发版本的

**Comment by hezedu** [comment]
代码确实是改了 https://github.com/node-webot/wechat-corp-service/commit/75a1cc796cf68b8a330a530eaa813833db65b811

**Comment by hezedu** [comment]
OK

**Comment by JacksonTian** [comment]
发布了。

**Comment by hezedu** [comment]
似乎并没有publish

**Comment by JacksonTian** [comment]
刚才timeout了
