### ISSUE TITLE
请问这个模块是支持微信第三方平台的吗？

### ISSUE THREAD

**Issue by klausgao** [node-webot/wechat-corp-service#2]
即代公众号发起网页授权、代公众号调用接口、代公众号使用JS SDK这些，
求告知

**Comment by JacksonTian** [comment]
是的

发自我的 iPhone

**Comment by klausgao** [comment]
看了一下源码，感觉和微信第三方开发平台对应的文档套不上啊？
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&lang=zh_CN&token=a130ad50bc4a9539793278ce85836a36bd84cd2e

**Comment by JacksonTian** [comment]
因为没开发者用 所以没持续开发 有兴趣可以加入

发自我的 iPhone

**Comment by klausgao** [comment]
怕能力不够啊哈哈，不过我慢慢开发试试

**Comment by JacksonTian** [comment]
当用户 及时给反馈 也挺好的。

**Comment by JacksonTian** [comment]
我们更新了readme。有问题再详细反馈吧。
